### ISSUE TITLE
数据源缺失,希望自带数据

### ISSUE THREAD

**Issue by laohur** [ZhiqingXiao/pytorch-book#1]
https://github.com/ZhiqingXiao/pytorch-book/blob/master/chapter06_logistic/stock_volume.ipynb
这里的股票数据源升级了,需要注册才能下载,希望直接附带数据.

**Comment by ZhiqingXiao** [comment]
收到。谢谢反馈。
Well received. Thank you for the feedback.

数据目前放在读者服务QQ群（698847007）群文件里./data/FB.csv。改日也会传到这个repo里。

20190315: 数据已上传 https://raw.githubusercontent.com/zhiqingxiao/pytorch-book/master/chapter06_logistic/FB.csv
