### ISSUE TITLE
内容书写错误

### ISSUE THREAD

**Issue by tangyusi97** [ZhiqingXiao/pytorch-book#2]
## 第61页第1行
> 第i个数据条目的特征还可以表示为X[:]i,=(x[i,0],...,x[i,m-1],x[i,m])

## 第83页第6行
> p[0]+p[1]+...=p[c-1]=0

**Comment by ZhiqingXiao** [comment]
@tangyusi97 以上两处原书确实有误。我已根据您的建议更新了勘误wiki页面。感谢您提供勘误信息。
